# Generated by Django 4.2.18 on 2025-02-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=20)),
                ('prod_image', models.ImageField(upload_to='photos')),
                ('prod_price', models.IntegerField()),
                ('prod_desc', models.TextField()),
                ('prod_state', models.CharField(max_length=20)),
                ('prod_cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('sell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
