# Generated by Django 4.2.18 on 2025-04-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_wishlist_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('comment', models.CharField(default='', max_length=300)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.ordermodel')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.register')),
            ],
        ),
    ]
